# Generated by Django 4.1.7 on 2023-03-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoin',
            name='quantidade',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
