# Generated by Django 4.1.7 on 2023-03-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bitcoin_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoin',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='bitcoin',
            name='nome',
        ),
    ]
